### ISSUE TITLE
Add code of conduct and contributing guidelines

### ISSUE THREAD

**Issue by stijnvanhoey** [adokter/bioRad#87]
As we want to invite the community to use the package, we should as well inform them on how to contribute (issues, docs, PR...) and behave (conduct)

**Comment by stijnvanhoey** [comment]
At Lifewatch we already use the following:

- Code of conduct, see https://github.com/inbo/wateRinfo/blob/master/CONDUCT.md
- Contribution guidelines, see https://github.com/inbo/wateRinfo/blob/master/CONTRIBUTING.md

@peterdesmet and @adokter ok that I reuse/adapt these as the biorad code of conduct and contributing guidelines?

*Note:* adding these docs require the adaptation of the `.Rbuildignore` (cfr. [here](https://github.com/inbo/wateRinfo/blob/master/.Rbuildignore))

**Comment by peterdesmet** [comment]
Good idea! 👍 I think this files will also be added automatically to the bioRad website.

**Comment by peterdesmet** [comment]
Note: it might be good to move these to .github/CONDUCT and .github/CONTRIBUTING to avoid cluttering the root.

**Comment by peterdesmet** [comment]
Also, GitHub seems to expect a  `CODE_OF_CONDUCT.md` (not `CONDUCT.md`) file: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project

**Comment by stijnvanhoey** [comment]
Will this still work with the pkgdown website?

As such, we can actually also add PR and issue templates in the `.github` directory, as we use it for the [pydov package](https://github.com/DOV-Vlaanderen/pydov/tree/master/.github)

**Comment by stijnvanhoey** [comment]
I see! That's why github is still asking for a code of conduct on the waterinfo repo
![image](https://user-images.githubusercontent.com/754862/45917576-7c918800-be7a-11e8-942c-e3d67b1a60c0.png)

**Comment by stijnvanhoey** [comment]
@peterdesmet to include these into the pkdown website, I would:

- Add an additional section to the readme (the `.md` in this case), which refers to the code of conduct:

```
## Furthermore...

This package is an experimental open-source project. All functionalities are provided as is, without any guarantee.

Please note that this project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By participating in this project you agree to abide by its terms.

Please [report any issues or bugs](https://github.com/adokter/bioRad/issues/new).
```
as such, the conduct page will open on clicking the link.

- Add a navbar section in the `_pkgdown` file to have the contributing guidelines in the header navbar:

```
navbar:
  title: ~
  type: default
  left:
  - text: Reference
    href: reference/index.html
  - text: Articles
    href: articles/index.html
    menu:
    - text: Overview of Biorad functionality
      href: articles/functionality_overview.html
  - text: Contributing
    href: CONTRIBUTING.html
  right:
  - icon: fa-github fa-lg
    href: https://github.com/adokter/bioRad
```

ok?
